### ISSUE TITLE
Add an installation and/or configuration file

### ISSUE THREAD

**Issue by Teffluvium** [Mr-knick/simple_password_manager#2]
Consider adding a minimal `requirements.txt` file or, better yet, a basic project config file.

Here is an example `pyproject.toml` file that I used to configure and run using the `uv` packagte manager:
```toml
[project]
name = "simple-password-manager"
version = "0.1.0"
description = "A simple password manager written in Python."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "cryptography>=44.0.2",
    "docopt>=0.6.2",
    "tcl>=0.2",    # Tkinter package
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
```
